name: Trigger Workflow in Repository B

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main
      - '20**-main'
  push:
    branches:
      - main
      

permissions: write-all
jobs:
  call_workflow_in_b:
    # Reference the reusable workflow in Repository.
    uses: ruskinb1/test-passing-secret/.github/workflows/print-B-secret.yml@main # Point to the reusable workflow in Repository B
