name: Trigger Workflow in Repository B

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
    branches:
      - main
      - '20**-main'
      

permissions: write-all
jobs:
  call_workflow_in_b:
    # Reference the reusable workflow in Repository B
    uses: ruskinb1/test-passing-secret/.github/workflows/print-B-secret.yml@main # Point to the reusable workflow in Repository B
